name: Continuous Integration

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  quality-checks:
    name: Continuous Integration Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
        name: Install pnpm
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version-file: .nvmrc
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Lint and Format
        id: pnpm-lint
        run: pnpm lint

      - name: Test
        id: pnpm-test
        run: pnpm test

      - name: Test Coverage
        id: pnpm-test-coverage
        run: pnpm coverage

      - name: Build
        id: pnpm-build
        run: pnpm package
